# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 895629978d46220963bd6d8f9b8f3f56ecfc1734701dbb77a04c3d5808d1627d7618bf2c47f3a66e57a22c018123a8d9470b7395b1edddc4088c13e4f882d1d2

test:
  secret_key_base: b23ece47cb9b74c7275df902b29f0d182bce3d959c866aaf3e7fbdd0a2eabe44a481262883d926ba38dab5ded4f1ee821c1031cbb8a4ad52fb6ed8cf50ef8463

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
